# Generated by Django 4.2.10 on 2024-04-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0004_alter_section_class_number_delete_courseequivalent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='req_dict',
            field=models.JSONField(null=True),
        ),
    ]
