# Generated by Django 4.2.11 on 2024-04-29 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0005_customuser_req_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=16)),
                ('index', models.PositiveIntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_configurations', to='compass.academicterm')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_configurations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CalendarConfiguration',
                'ordering': ['index'],
                'unique_together': {('user', 'term', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CalendarSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='compass.calendarconfiguration')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compass.section')),
            ],
            options={
                'db_table': 'CalendarSelection',
                'unique_together': {('configuration', 'section')},
            },
        ),
        migrations.CreateModel(
            name='CalendarFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('filter_value', models.CharField(blank=True, db_index=True, max_length=100)),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='compass.calendarconfiguration')),
            ],
            options={
                'db_table': 'CalendarFilter',
                'unique_together': {('configuration', 'filter_type')},
            },
        ),
    ]
