# Generated by Django 4.2.13 on 2024-08-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hoagieplan", "0007_scheduleselection_semesterconfiguration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="certificates",
            field=models.ManyToManyField(to="hoagieplan.certificate"),
        ),
    ]
