# Generated by Django 5.1.1 on 2024-11-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hoagieplan", "0008_customuser_certificates"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="seen_tutorial",
            field=models.BooleanField(default=False),
        ),
    ]
